@API_URL = http://localhost:3001/student 

###

POST  http://localhost:3001/student/requestclass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InR1YmVsaWdodGJveTA1NkBnbWFpbC5jb20iLCJQb3NpdGlvbiI6MCwiaWQiOjEsImlhdCI6MTY0MjY1NDM2NywiZXhwIjoxNjQyNzk4MzY3fQ.4RlPNAgyUhiK18-ekbMN1vawM0-TnCmzITxXMzULqZg
Content-Type: application/json

{                           
    "teacher_id":1,
    "democlass":true,
    "starttime":"2022-01-17 22:15:33.161",
    "topic":"cse"
}

###

POST  http://localhost:3001/student/requestclass
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQyQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MTAsImlhdCI6MTY1OTAwMDkzMSwiZXhwIjoxNjU5MTQ0OTMxfQ.TWcn979UDff-J11XSfVDIjdqCfdYXmR_GwI40aUnmak
Content-Type: application/json

{                           
    "teacher_id":3,
    "democlass":false,
    "starttime":"2022-01-17 22:15:33.161",
    "topic":"cse",
    "classroom_id":2
}

###

POST  http://localhost:3001/student/createclassroom
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFhYWFAZ21haWwuY29tIiwiUG9zaXRpb24iOjAsImlkIjozLCJpYXQiOjE2NTc1NTc0MzYsImV4cCI6MTY1NzcwMTQzNn0.kVTaz0NSHQmDQ5iotMj4BzOJAayFg1uCxUZOS4YZ1V0
Content-Type: application/json

{                           
    "teacher_id":1
}

###

POST  http://localhost:3001/student/classrooms
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQyQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MTAsImlhdCI6MTY1OTAwMDkzMSwiZXhwIjoxNjU5MTQ0OTMxfQ.TWcn979UDff-J11XSfVDIjdqCfdYXmR_GwI40aUnmak
Content-Type: application/json

{                           
    
}


###
POST  http://localhost:3001/student/classroom/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQyQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MTAsImlhdCI6MTY1OTAwMDkzMSwiZXhwIjoxNjU5MTQ0OTMxfQ.TWcn979UDff-J11XSfVDIjdqCfdYXmR_GwI40aUnmak
Content-Type: application/json

{                           
    "classroom_id":1
}

###

POST  http://localhost:3001/student/classes
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQyQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MTAsImlhdCI6MTY1OTAwMDkzMSwiZXhwIjoxNjU5MTQ0OTMxfQ.TWcn979UDff-J11XSfVDIjdqCfdYXmR_GwI40aUnmak
Content-Type: application/json

{                           
    
}

###

POST  {{API_URL}}/update/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InR1YmVsaWdodGJveTA1NkBnbWFpbC5jb20iLCJQb3NpdGlvbiI6MiwiaWQiOjEsImlhdCI6MTY0NTE4NTMyNCwiZXhwIjoxNjQ1MzI5MzI0fQ.7Z1oZnLGcxRy30dQxzK6a-7YLgtZMtm2Q4EMjNyPCgg
Content-Type: application/json

{                           
    "FirstName":"dev",
    "LastName":"Prem",
    "Standard":1,
    "Board":"CBSE",
    "GenderPerference":1,
    "phno":"6382093752",
    "Address":"vgfjghv",
    "district":"njhgfjh",
    "city":"kjfghdhf",
    "country":"jvghdfx",
    "state":"mjkgc",
    "postal_code":641659
}

###

POST  {{API_URL}}/info
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQxQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MiwiaWF0IjoxNjYxNTI3OTM0LCJleHAiOjE2NjE2NzE5MzR9.OYMGs76nqxnHmA3Yh-l4XQY_TTzp8NML_R3rtcc8yec
Content-Type: application/json

{           
                  
    
}

###

POST  {{API_URL}}/info/price
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQxQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MiwiaWF0IjoxNjYxNTI3OTM0LCJleHAiOjE2NjE2NzE5MzR9.OYMGs76nqxnHmA3Yh-l4XQY_TTzp8NML_R3rtcc8yec
Content-Type: application/json

{                           
    "standard":1,
    "board":1
}

###

POST  {{API_URL}}/info/property
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InR1YmVsaWdodGJveTAwNTZAZ21haWwuY29tIiwiUG9zaXRpb24iOjAsImlkIjoyLCJpYXQiOjE2NDU4MDUyNzMsImV4cCI6MTY0NTk0OTI3M30.UIAgIRGqGimpGnhbPhgyiYvFWRFjOMLhtQXIvDI7Ujo
Content-Type: application/json

{                           
    
}


###

POST  {{API_URL}}/info/getbyid
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6InN0dWRlbnQxQGdtYWlsLmNvbSIsIlBvc2l0aW9uIjowLCJpZCI6MiwiaWF0IjoxNjYxNTI3OTM0LCJleHAiOjE2NjE2NzE5MzR9.OYMGs76nqxnHmA3Yh-l4XQY_TTzp8NML_R3rtcc8yec
Content-Type: application/json

{           
       "student_id":1          
    
}


###

POST  {{API_URL}}/submit/rating
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJFbWFpbCI6ImFhYWFAZ21haWwuY29tIiwiUG9zaXRpb24iOjAsImlkIjozLCJpYXQiOjE2NTg1MTYwMzQsImV4cCI6MTY1ODY2MDAzNH0.ApEBmZiw4vvCTE-r6nLhR6QyTRojIm9TOA2lpPjA9cg
Content-Type: application/json

{           
                               
    "id_student":2,
    "id_teacher":3,
    "ratings":5,
    "comments":"Good",
    "to":3,
    "id_classes":1
}


